name: Runner Diagnostic

on:
  push:
    branches:
      - sandbox-flutter-game
    paths:
      - ".github/workflows/build-flutter-game.yml"
  workflow_dispatch:

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    steps:
      - name: Runner info
        run: |
          uname -a
          java -version
          df -h
